services:
  app:
    build: .
    ports:
      - "8082:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/RateLimiter
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgresql987
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=RateLimiter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresql987
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"